# Edit distance search
Manipulating inference results, creating training and testing labels

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
from tqdm import tqdm
import os

In [3]:
basepath = r"C:\Users\Parv\Doc\HelixWorks\Basecalling\code\motifcaller\data\empirical\01-04run\edit_distance_outputs"

In [4]:
def clean_prediction(edit_motif_search_prediction):

    cleaned_prediction = []
    for i in edit_motif_search_prediction:
        if i == 'fake':
            cleaned_prediction.append([])
        else:
            cleaned_prediction.append([int(i[1])])

    return cleaned_prediction

In [5]:

def get_edit_dataframe(edit_inference_filename):

    with open(edit_inference_filename, 'r') as f:
        lines = f.readlines()

    motif_predictions = []
    orientations = []
    read_ids = []
    ont_barcode = []

    for line in tqdm(lines):
        split_line = line.split()
        read_id = split_line[0][3:]
        orientation = split_line[1]
        prediction = split_line[4][8:].split('->')
        if not (prediction[0].startswith('f') or prediction[0].startswith('m')):
            prediction = prediction[1:]

        cleaned_prediction = clean_prediction(prediction)
        
        motif_predictions.append(cleaned_prediction)
        orientations.append(orientation)
        read_ids.append(read_id)
    
    df = pd.DataFrame({"read_id": read_ids, "orientation": orientations, "motif_seq": motif_predictions})
    df = df.drop_duplicates(subset=['read_id'])
    return df

In [6]:
master_df = pd.DataFrame()

for file in tqdm(os.listdir(basepath)):
    df = get_edit_dataframe(os.path.join(basepath, file))
    master_df = pd.concat([master_df, df])

100%|██████████| 2769/2769 [00:00<00:00, 197843.85it/s]
100%|██████████| 2920/2920 [00:00<00:00, 205323.94it/s]
100%|██████████| 2870/2870 [00:00<00:00, 50991.66it/s]
100%|██████████| 2691/2691 [00:00<00:00, 199027.90it/s]
100%|██████████| 2684/2684 [00:00<00:00, 206567.43it/s]
100%|██████████| 2812/2812 [00:00<00:00, 45834.58it/s]
100%|██████████| 2749/2749 [00:00<00:00, 196037.50it/s]
100%|██████████| 2721/2721 [00:00<00:00, 194242.21it/s]
100%|██████████| 2748/2748 [00:00<00:00, 42509.05it/s]
100%|██████████| 1300/1300 [00:00<00:00, 217252.18it/s]
100%|██████████| 2945/2945 [00:00<00:00, 184026.48it/s]
100%|██████████| 2671/2671 [00:00<00:00, 190679.39it/s]
100%|██████████| 2708/2708 [00:00<00:00, 41019.50it/s]
100%|██████████| 2715/2715 [00:00<00:00, 180978.60it/s]
100%|██████████| 1399/1399 [00:00<00:00, 199538.59it/s]
100%|██████████| 2707/2707 [00:00<00:00, 193298.73it/s]
100%|██████████| 200/200 [00:00<00:00, 204003.11it/s]
100%|██████████| 2734/2734 [00:00<00:00, 195289.89it/s]
100%|██████████| 2757/2757 [00:00<00:00, 33579.08it/s]
100%|██████████| 2670/2670 [00:00<00:00, 196311.60it/s]
100%|██████████| 2727/2727 [00:00<00:00, 181787.17it/s]
100%|██████████| 2715/2715 [00:00<00:00, 193899.70it/s]
100%|██████████| 2975/2975 [00:00<00:00, 186031.37it/s]
100%|██████████| 2699/2699 [00:00<00:00, 32295.82it/s]
100%|██████████| 2867/2867 [00:00<00:00, 168590.71it/s]
100%|██████████| 2597/2597 [00:00<00:00, 216269.06it/s]
100%|██████████| 2870/2870 [00:00<00:00, 191237.77it/s]
100%|██████████| 2855/2855 [00:00<00:00, 204061.52it/s]
100%|██████████| 2148/2148 [00:00<00:00, 195261.49it/s]
100%|██████████| 2901/2901 [00:00<00:00, 29448.42it/s]
100%|██████████| 2873/2873 [00:00<00:00, 205278.11it/s]
100%|██████████| 2962/2962 [00:00<00:00, 197562.63it/s]
100%|██████████| 2943/2943 [00:00<00:00, 183950.83it/s]
100%|██████████| 1199/1199 [00:00<00:00, 184049.57it/s]
100%|██████████| 2937/2937 [00:00<00:00, 209843.81it/s]
100%|██████████| 2488/2488 [00:00<00:00, 191507.37it/s]
100%|██████████| 2660/2660 [00:00<00:00, 204641.48it/s]
100%|██████████| 2986/2986 [00:00<00:00, 198840.88it/s]
100%|██████████| 2846/2846 [00:00<00:00, 24633.58it/s]
100%|██████████| 2908/2908 [00:00<00:00, 194053.46it/s]
100%|██████████| 2897/2897 [00:00<00:00, 214056.17it/s]
100%|██████████| 2945/2945 [00:00<00:00, 196319.48it/s]
100%|██████████| 3004/3004 [00:00<00:00, 200293.92it/s]
100%|██████████| 1049/1049 [00:00<00:00, 174623.94it/s]
100%|██████████| 2916/2916 [00:00<00:00, 194435.73it/s]
100%|██████████| 2900/2900 [00:00<00:00, 193344.27it/s]
100%|██████████| 2937/2937 [00:00<00:00, 195807.97it/s]
100%|██████████| 2692/2692 [00:00<00:00, 199140.49it/s]
100%|██████████| 2950/2950 [00:00<00:00, 23316.57it/s]
100%|██████████| 2927/2927 [00:00<00:00, 195305.81it/s]
100%|██████████| 2946/2946 [00:00<00:00, 178383.11it/s]
100%|██████████| 2788/2788 [00:00<00:00, 185933.34it/s]
100%|██████████| 2836/2836 [00:00<00:00, 189092.39it/s]
100%|██████████| 2853/2853 [00:00<00:00, 188970.21it/s]
100%|██████████| 2901/2901 [00:00<00:00, 181306.73it/s]
100%|██████████| 2939/2939 [00:00<00:00, 195984.92it/s]
100%|██████████| 2892/2892 [00:00<00:00, 186370.55it/s]
100%|██████████| 2908/2908 [00:00<00:00, 171040.04it/s]
100%|██████████| 2612/2612 [00:00<00:00, 200967.13it/s]
100%|██████████| 2949/2949 [00:00<00:00, 202903.58it/s]
100%|██████████| 2831/2831 [00:00<00:00, 19962.30it/s]
100%|██████████| 3010/3010 [00:00<00:00, 214387.57it/s]
100%|██████████| 2845/2845 [00:00<00:00, 201227.57it/s]
100%|██████████| 698/698 [00:00<00:00, 174804.41it/s]
100%|██████████| 2815/2815 [00:00<00:00, 175947.63it/s]
100%|██████████| 2823/2823 [00:00<00:00, 165889.38it/s]
100%|██████████| 2833/2833 [00:00<00:00, 188916.39it/s]
100%|██████████| 450/450 [00:00<00:00, 225581.07it/s]
100%|██████████| 2697/2697 [00:00<00:00, 163362.52it/s]
100%|██████████| 2647/2647 [00:00<00:00, 176473.85it/s]
100%|██████████| 2776/2776 [00:00<00:00, 198340.62it/s]
100%|██████████| 2805/2805 [00:00<00:00, 200426.28it/s]
100%|██████████| 2934/2934 [00:00<00:00, 195617.29it/s]
100%|██████████| 2810/2810 [00:00<00:00, 200790.39it/s]
100%|██████████| 1198/1198 [00:00<00:00, 171178.59it/s]
100%|██████████| 2715/2715 [00:00<00:00, 181099.48it/s]
100%|██████████| 2790/2790 [00:00<00:00, 199317.13it/s]
100%|██████████| 2764/2764 [00:00<00:00, 194455.64it/s]
100%|██████████| 2875/2875 [00:00<00:00, 17209.81it/s]
100%|██████████| 2824/2824 [00:00<00:00, 216967.95it/s]
100%|██████████| 2560/2560 [00:00<00:00, 213022.88it/s]
100%|██████████| 2804/2804 [00:00<00:00, 193028.30it/s]
100%|██████████| 2837/2837 [00:00<00:00, 189279.43it/s]
100%|██████████| 2843/2843 [00:00<00:00, 177470.29it/s]
100%|██████████| 1297/1297 [00:00<00:00, 215403.38it/s]
100%|██████████| 2768/2768 [00:00<00:00, 172917.20it/s]
100%|██████████| 2800/2800 [00:00<00:00, 155624.55it/s]
100%|██████████| 2754/2754 [00:00<00:00, 211892.60it/s]
100%|██████████| 2812/2812 [00:00<00:00, 200953.84it/s]
100%|██████████| 449/449 [00:00<00:00, 149203.18it/s]
100%|██████████| 2839/2839 [00:00<00:00, 171554.95it/s]
100%|██████████| 2703/2703 [00:00<00:00, 180178.69it/s]
100%|██████████| 2871/2871 [00:00<00:00, 179423.77it/s]
100%|██████████| 2915/2915 [00:00<00:00, 194149.91it/s]
100%|██████████| 1398/1398 [00:00<00:00, 199246.90it/s]
100%|██████████| 2955/2955 [00:00<00:00, 210623.98it/s]
100%|██████████| 2876/2876 [00:00<00:00, 205335.05it/s]
100%|██████████| 2146/2146 [00:00<00:00, 194881.17it/s]
100%|██████████| 2976/2976 [00:00<00:00, 185515.85it/s]
100%|██████████| 2880/2880 [00:00<00:00, 14683.21it/s]
100%|██████████| 2754/2754 [00:00<00:00, 161952.68it/s]
100%|██████████| 2811/2811 [00:00<00:00, 175668.82it/s]
100%|██████████| 2730/2730 [00:00<00:00, 194974.29it/s]
100%|██████████| 2843/2843 [00:00<00:00, 177782.51it/s]
100%|██████████| 2833/2833 [00:00<00:00, 182319.07it/s]
100%|██████████| 2595/2595 [00:00<00:00, 216141.13it/s]
100%|██████████| 2872/2872 [00:00<00:00, 179561.18it/s]
100%|██████████| 2932/2932 [00:00<00:00, 195446.66it/s]
100%|██████████| 2913/2913 [00:00<00:00, 182029.58it/s]
100%|██████████| 2822/2822 [00:00<00:00, 175217.99it/s]
100%|██████████| 2834/2834 [00:00<00:00, 188865.97it/s]
100%|██████████| 2595/2595 [00:00<00:00, 199359.27it/s]
100%|██████████| 2927/2927 [00:00<00:00, 183024.40it/s]
100%|██████████| 2847/2847 [00:00<00:00, 189720.27it/s]
100%|██████████| 2738/2738 [00:00<00:00, 188385.90it/s]
100%|██████████| 2836/2836 [00:00<00:00, 202286.38it/s]
100%|██████████| 2958/2958 [00:00<00:00, 184574.83it/s]
100%|██████████| 3026/3026 [00:00<00:00, 201699.86it/s]
100%|██████████| 2940/2940 [00:00<00:00, 195998.63it/s]
100%|██████████| 3047/3047 [00:00<00:00, 190499.56it/s]
100%|██████████| 2958/2958 [00:00<00:00, 197048.29it/s]
100%|██████████| 2870/2870 [00:00<00:00, 178098.13it/s]
100%|██████████| 3017/3017 [00:00<00:00, 13131.82it/s]
100%|██████████| 2778/2778 [00:00<00:00, 197839.83it/s]
100%|██████████| 2799/2799 [00:00<00:00, 199926.04it/s]
100%|██████████| 2582/2582 [00:00<00:00, 184376.00it/s]
100%|██████████| 1900/1900 [00:00<00:00, 211132.01it/s]
100%|██████████| 2762/2762 [00:00<00:00, 184237.47it/s]
100%|██████████| 2838/2838 [00:00<00:00, 189213.71it/s]
100%|██████████| 2928/2928 [00:00<00:00, 209207.90it/s]
100%|██████████| 2885/2885 [00:00<00:00, 206068.82it/s]
100%|██████████| 2917/2917 [00:00<00:00, 208411.29it/s]
100%|██████████| 2746/2746 [00:00<00:00, 183097.40it/s]
100%|██████████| 2804/2804 [00:00<00:00, 151375.65it/s]
100%|██████████| 2901/2901 [00:00<00:00, 181290.52it/s]
100%|██████████| 2496/2496 [00:00<00:00, 199295.31it/s]
100%|██████████| 2590/2590 [00:00<00:00, 198760.36it/s]
100%|██████████| 2889/2889 [00:00<00:00, 180468.01it/s]
100%|██████████| 2957/2957 [00:00<00:00, 197219.73it/s]
100%|██████████| 2930/2930 [00:00<00:00, 209012.55it/s]
100%|██████████| 2954/2954 [00:00<00:00, 196435.52it/s]
100%|██████████| 450/450 [00:00<00:00, 225284.89it/s]
100%|██████████| 2884/2884 [00:00<00:00, 205878.18it/s]
100%|██████████| 2813/2813 [00:00<00:00, 200984.21it/s]
100%|██████████| 2874/2874 [00:00<00:00, 191647.40it/s]
100%|██████████| 2819/2819 [00:00<00:00, 201433.49it/s]
100%|██████████| 2735/2735 [00:00<00:00, 182216.21it/s]
100%|██████████| 2780/2780 [00:00<00:00, 185293.75it/s]
100%|██████████| 1900/1900 [00:00<00:00, 189977.53it/s]
100%|██████████| 2839/2839 [00:00<00:00, 195447.34it/s]
100%|██████████| 2757/2757 [00:00<00:00, 183848.39it/s]
100%|██████████| 2475/2475 [00:00<00:00, 206305.94it/s]
100%|██████████| 2551/2551 [00:00<00:00, 182180.95it/s]
100%|██████████| 2574/2574 [00:00<00:00, 183601.55it/s]
100%|██████████| 2428/2428 [00:00<00:00, 8370.27it/s]
100%|██████████| 2740/2740 [00:00<00:00, 195541.98it/s]
100%|██████████| 2506/2506 [00:00<00:00, 199789.50it/s]
100%|██████████| 2853/2853 [00:00<00:00, 167769.81it/s]
100%|██████████| 2497/2497 [00:00<00:00, 171868.93it/s]
100%|██████████| 2350/2350 [00:00<00:00, 180706.10it/s]
100%|██████████| 2332/2332 [00:00<00:00, 194486.54it/s]
100%|██████████| 2640/2640 [00:00<00:00, 188781.22it/s]
100%|██████████| 2510/2510 [00:00<00:00, 192942.29it/s]
100%|██████████| 2330/2330 [00:00<00:00, 194146.02it/s]
100%|██████████| 2607/2607 [00:00<00:00, 200567.71it/s]
100%|██████████| 2454/2454 [00:00<00:00, 188589.21it/s]
100%|██████████| 2687/2687 [00:00<00:00, 191994.80it/s]
100%|██████████| 2342/2342 [00:00<00:00, 156033.04it/s]
100%|██████████| 2652/2652 [00:00<00:00, 189539.14it/s]
100%|██████████| 2843/2843 [00:00<00:00, 189643.54it/s]
100%|██████████| 2273/2273 [00:00<00:00, 189389.00it/s]
100%|██████████| 1996/1996 [00:00<00:00, 181491.30it/s]
100%|██████████| 2148/2148 [00:00<00:00, 195147.29it/s]
100%|██████████| 1798/1798 [00:00<00:00, 188566.96it/s]
100%|██████████| 1969/1969 [00:00<00:00, 179172.21it/s]
100%|██████████| 2428/2428 [00:00<00:00, 221078.72it/s]
100%|██████████| 2222/2222 [00:00<00:00, 201852.75it/s]
100%|██████████| 2756/2756 [00:00<00:00, 183720.37it/s]
100%|██████████| 2270/2270 [00:00<00:00, 206132.85it/s]
100%|██████████| 1876/1876 [00:00<00:00, 170565.21it/s]
100%|██████████| 1685/1685 [00:00<00:00, 210709.35it/s]
100%|██████████| 2925/2925 [00:00<00:00, 195159.94it/s]
100%|██████████| 1223/1223 [00:00<00:00, 174983.24it/s]
100%|██████████| 2839/2839 [00:00<00:00, 202383.35it/s]
100%|██████████| 2840/2840 [00:00<00:00, 189133.60it/s]
100%|██████████| 2829/2829 [00:00<00:00, 188607.67it/s]
100%|██████████| 2817/2817 [00:00<00:00, 201314.59it/s]
100%|██████████| 2875/2875 [00:00<00:00, 179684.46it/s]
100%|██████████| 2661/2661 [00:00<00:00, 166483.34it/s]
100%|██████████| 2824/2824 [00:00<00:00, 187570.70it/s]
100%|██████████| 2928/2928 [00:00<00:00, 195009.56it/s]
100%|██████████| 2747/2747 [00:00<00:00, 210777.91it/s]
100%|██████████| 2836/2836 [00:00<00:00, 188822.24it/s]
100%|██████████| 2866/2866 [00:00<00:00, 190849.95it/s]
100%|██████████| 2832/2832 [00:00<00:00, 202262.48it/s]
100%|██████████| 2874/2874 [00:00<00:00, 191067.20it/s]
100%|██████████| 2877/2877 [00:00<00:00, 7668.59it/s]
100%|██████████| 2890/2890 [00:00<00:00, 192561.26it/s]
100%|██████████| 2895/2895 [00:00<00:00, 180107.84it/s]
100%|██████████| 2536/2536 [00:00<00:00, 194833.77it/s]
100%|██████████| 2904/2904 [00:00<00:00, 193629.42it/s]
100%|██████████| 2494/2494 [00:00<00:00, 191958.64it/s]
100%|██████████| 1298/1298 [00:00<00:00, 185114.13it/s]
100%|██████████| 2691/2691 [00:00<00:00, 192310.10it/s]
100%|██████████| 2913/2913 [00:00<00:00, 193952.02it/s]
100%|██████████| 2885/2885 [00:00<00:00, 192331.99it/s]
100%|██████████| 2914/2914 [00:00<00:00, 182165.35it/s]
100%|██████████| 2761/2761 [00:00<00:00, 197309.23it/s]
100%|██████████| 2829/2829 [00:00<00:00, 202110.17it/s]
100%|██████████| 2868/2868 [00:00<00:00, 204725.55it/s]
100%|██████████| 700/700 [00:00<00:00, 175179.76it/s]
100%|██████████| 2939/2939 [00:00<00:00, 195897.71it/s]
100%|██████████| 2819/2819 [00:00<00:00, 187896.18it/s]
100%|██████████| 2891/2891 [00:00<00:00, 206128.80it/s]
100%|██████████| 2893/2893 [00:00<00:00, 180836.39it/s]
100%|██████████| 2694/2694 [00:00<00:00, 207306.63it/s]
100%|██████████| 2932/2932 [00:00<00:00, 209408.09it/s]
100%|██████████| 2837/2837 [00:00<00:00, 188984.82it/s]
100%|██████████| 2939/2939 [00:00<00:00, 172800.36it/s]
100%|██████████| 2870/2870 [00:00<00:00, 179398.70it/s]
100%|██████████| 1646/1646 [00:00<00:00, 182761.73it/s]
100%|██████████| 950/950 [00:00<00:00, 190340.54it/s]
100%|██████████| 2887/2887 [00:00<00:00, 206239.77it/s]
100%|██████████| 2861/2861 [00:00<00:00, 204128.60it/s]
100%|██████████| 2884/2884 [00:00<00:00, 205874.68it/s]
100%|██████████| 2862/2862 [00:00<00:00, 204446.87it/s]
100%|██████████| 2873/2873 [00:00<00:00, 191319.13it/s]
100%|██████████| 599/599 [00:00<00:00, 199570.11it/s]
100%|██████████| 2839/2839 [00:00<00:00, 177460.94it/s]
100%|██████████| 2968/2968 [00:00<00:00, 197047.84it/s]
100%|██████████| 2861/2861 [00:00<00:00, 178684.33it/s]
100%|██████████| 2814/2814 [00:00<00:00, 193380.27it/s]
100%|██████████| 2349/2349 [00:00<00:00, 190263.60it/s]
100%|██████████| 2941/2941 [00:00<00:00, 188967.92it/s]
100%|██████████| 2195/2195 [00:00<00:00, 199033.58it/s]
100%|██████████| 235/235 [00:11<00:00, 20.84it/s]

In [10]:
master_df.to_pickle(r"C:\Users\Parv\Doc\HelixWorks\Basecalling\code\motifcaller\data\empirical\01-04run\edit_medium.pkl")

## Balancing edit-train df

In [5]:
from data_functions import get_cleaned_encoded_file

In [6]:
encoded_df = pd.read_csv(r"C:\Users\Parv\Doc\HelixWorks\Basecalling\code\motifcaller\data\empirical\EIC01-01-1280-T1_encoded.tsv", sep='\t')

In [136]:
t = get_cleaned_encoded_file(encoded_df)

In [137]:
t = t[['ONT_Barcode', 'HW_Address', 'payload']]

In [9]:
t

,ONT_Barcode,HW_Address,payload
0,1,barcode_external01_internal01,"[[2, 3, 4, 5], [1, 2, 7, 8], [1, 4, 5, 6], [4,..."
1,1,barcode_external02_internal01,"[[3, 4, 7, 8], [2, 3, 4, 8], [2, 4, 6, 7], [1,..."
2,1,barcode_external03_internal01,"[[1, 3, 5, 8], [2, 4, 5, 6], [1, 5, 6, 8], [1,..."
3,1,barcode_external04_internal01,"[[1, 4, 5, 8], [3, 4, 7, 8], [1, 4, 7, 8], [1,..."
4,1,barcode_external05_internal01,"[[2, 4, 5, 6], [3, 4, 6, 7], [4, 5, 6, 8], [1,..."
...,...,...,...
1275,77,barcode_external04_internal08,"[[1, 2, 3, 6], [2, 4, 5, 7], [1, 3, 4, 7], [1,..."
1276,77,barcode_external05_internal08,"[[4, 6, 7, 8], [1, 2, 4, 8], [3, 4, 5, 7], [2,..."
1277,77,barcode_external06_internal08,"[[1, 4, 7, 8], [4, 6, 7, 8], [1, 2, 4, 8], [2,..."
1278,77,barcode_external07_internal08,"[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1,..."
1279,77,barcode_external08_internal08,"[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1,..."

In [10]:
edit_train_df = pd.read_pickle(r"C:\Users\Parv\Doc\HelixWorks\Basecalling\code\motifcaller\data\empirical\full_datasets\edit_master_train.pkl")

In [11]:
edit_train_df.head()

,read_id,ONT_Barcode,HW_Address,orientation,start_end,library_motif,squiggle,motif_seq,strand,payload_motifs_found,edit_spacer_seq,edit_motifs_found,payload
0,0117ec74-7ef1-4e8c-b169-c8ca9a576de4,barcode01,barcode_external01_internal01,+|+|+,75-124|370-419|566-615,ltm8_2x1|ltm8_5x4|ltm8_9x1,"[452, 439, 450, 444, 451, 454, 471, 448, 418, ...","[10, 1, 10, 13, 4, 13, 17, 1, 17]",+,3,"[10, 1, 10, 11, 1, 11, 12, 3, 12, 13, 1, 13, 1...",9.0,"[[2, 3, 4, 5], [1, 2, 7, 8], [1, 4, 5, 6], [4,..."
1,0117ec74-7ef1-4e8c-b169-c8ca9a576de4,barcode01,barcode_external01_internal01,+|+|+,75-124|370-419|566-615,ltm8_2x1|ltm8_5x4|ltm8_9x1,"[452, 439, 450, 444, 451, 454, 471, 448, 418, ...","[10, 1, 10, 13, 4, 13, 17, 1, 17]",+,3,"[10, 1, 10, 11, 1, 11, 12, 3, 12, 13, 1, 13, 1...",9.0,"[[3, 6, 7, 8], [3, 4, 5, 8], [1, 2, 4, 6], [1,..."
2,0117ec74-7ef1-4e8c-b169-c8ca9a576de4,barcode01,barcode_external01_internal01,+|+|+,75-124|370-419|566-615,ltm8_2x1|ltm8_5x4|ltm8_9x1,"[452, 439, 450, 444, 451, 454, 471, 448, 418, ...","[10, 1, 10, 13, 4, 13, 17, 1, 17]",+,3,"[10, 1, 10, 11, 1, 11, 12, 3, 12, 13, 1, 13, 1...",9.0,"[[1, 2, 4, 5], [2, 4, 5, 6], [2, 5, 6, 8], [2,..."
3,0117ec74-7ef1-4e8c-b169-c8ca9a576de4,barcode01,barcode_external01_internal01,+|+|+,75-124|370-419|566-615,ltm8_2x1|ltm8_5x4|ltm8_9x1,"[452, 439, 450, 444, 451, 454, 471, 448, 418, ...","[10, 1, 10, 13, 4, 13, 17, 1, 17]",+,3,"[10, 1, 10, 11, 1, 11, 12, 3, 12, 13, 1, 13, 1...",9.0,"[[2, 3, 4, 8], [3, 5, 6, 7], [2, 3, 7, 8], [2,..."
4,0117ec74-7ef1-4e8c-b169-c8ca9a576de4,barcode01,barcode_external01_internal01,+|+|+,75-124|370-419|566-615,ltm8_2x1|ltm8_5x4|ltm8_9x1,"[452, 439, 450, 444, 451, 454, 471, 448, 418, ...","[10, 1, 10, 13, 4, 13, 17, 1, 17]",+,3,"[10, 1, 10, 11, 1, 11, 12, 3, 12, 13, 1, 13, 1...",9.0,"[[1, 4, 5, 6], [1, 5, 6, 8], [1, 3, 6, 8], [2,..."

In [12]:
edit_train_df = edit_train_df.drop(columns=['payload'])

In [13]:
edit_train_df['ONT_Barcode'] = edit_train_df['ONT_Barcode'].apply(lambda x: int(x[-2:]))

In [138]:
merged_df = pd.merge(filtered_df, t, on=['ONT_Barcode', 'HW_Address'])

Steps
1. Filter out reads where more than 8 motifs are identified
2. Keep the ones with no error
3. For the ones with error, check motif search label and encoded to make the perfect label with no errors
4. Double check that there are no errors for the whole dataset
5. Keep the address motifs identified
6. Some data of the distribution of reads

In [30]:
filtered_df = merged_df.loc[merged_df['edit_motifs_found'] > 9]

In [19]:
from transcript_sorting import sort_transcript_with_address
from utils import evaluate_prediction, create_spacer_sequence_with_address

In [142]:
filtered_df['edit_payload_seq'] = filtered_df['edit_spacer_seq'].apply(lambda x: sort_transcript_with_address(x))

C:\Users\Parv\AppData\Local\Temp\ipykernel_16804\3654313105.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['edit_payload_seq'] = filtered_df['edit_spacer_seq'].apply(lambda x: sort_transcript_with_address(x))

In [33]:
def remove_erroneous_motifs(prediction, original):
    corrected = [[] for i in range(8)]

    cycle_num = 0
    for i, j in zip(prediction, original):
        for k in i:
            if k in j:
                corrected[cycle_num].append(k)
        cycle_num += 1
    return corrected

In [72]:
from tqdm import tqdm

In [74]:
filtered_df.columns

Index(['read_id', 'ONT_Barcode', 'HW_Address', 'orientation', 'start_end',
       'library_motif', 'squiggle', 'motif_seq', 'strand',
       'payload_motifs_found', 'edit_spacer_seq', 'edit_motifs_found',
       'payload', 'edit_payload_seq'],
      dtype='object')

In [141]:
merged_df.columns

Index(['read_id', 'ONT_Barcode', 'HW_Address', 'orientation', 'start_end',
       'library_motif', 'squiggle', 'motif_seq', 'strand',
       'payload_motifs_found', 'edit_spacer_seq', 'edit_motifs_found',
       'payload_x', 'payload_y'],
      dtype='object')

In [145]:
counter = 0
mf = 0
me = 0
corrected_edit_payload_seq = []
unique_predictions = set()

edit_seqs = []
spacer_seqs = []
read_ids = []
payloads = []
squiggles = []
orientation = []

for ind, row in tqdm(filtered_df.iterrows(), total=len(filtered_df)):
    i = row['edit_payload_seq']
    j = row['payload']
    k = row['edit_spacer_seq']
    read_id = row['read_id']



    if str(i) not in unique_predictions:
        metrics = evaluate_prediction(i[2:], j)
        if metrics[1] > 0:
            continue
        mf += metrics[0]
        me += metrics[1]
        read_ids.append(read_id)
        edit_seqs.append(i)
        spacer_seqs.append(k)
        unique_predictions.add(str(i))
    #final = i[:2] + corrected
    #print(i)
    #print(final)
    #print()
    #corrected_edit_payload_seq.append(final)

100%|██████████| 110274/110274 [00:06<00:00, 17521.52it/s]

In [149]:
filtered_df = filtered_df.loc[filtered_df['read_id'].isin(read_ids)]

In [150]:
len(filtered_df)

90534

In [103]:
forward_df = filtered_df_.loc[filtered_df_['read_id'].isin(read_ids)]

In [105]:
forward_df = forward_df.loc[forward_df['orientation'].str.startswith('+')]

In [153]:
filtered_df.to_pickle(r'C:\Users\Parv\Doc\HelixWorks\Basecalling\code\motifcaller\data\empirical\edit_distance_motif_search\edit_train_filtered_reverse.pkl')

In [81]:
len(merged_unique_df)

2936700

In [68]:
t = [str(i) for i in filtered_df['edit_payload_seq'].to_list()[:2942440]]

In [157]:
filtered_reverse = filtered_df.loc[filtered_df['orientation'].str.startswith('-')]

In [160]:
filtered_reverse['edit_spacer_seq'] = filtered_reverse['edit_spacer_seq'].apply(lambda x: x[::-1])

C:\Users\Parv\AppData\Local\Temp\ipykernel_4900\2773630298.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_reverse['edit_spacer_seq'] = filtered_reverse['edit_spacer_seq'].apply(lambda x: x[::-1])

In [ ]:
filtered_forward['edit_spacer_seq'] = filtered_df['edit_payload_seq_no_error'].apply()

In [166]:
filtered_reverse.to_pickle(r"C:\Users\Parv\Doc\HelixWorks\Basecalling\code\motifcaller\data\empirical\edit_distance_motif_search\edit_train_filtered_reverse.pkl")

In [167]:
filtered_forward = pd.read_pickle(r"C:\Users\Parv\Doc\HelixWorks\Basecalling\code\motifcaller\data\empirical\edit_distance_motif_search\edit_train_filtered_forward.pkl")

### Adding edit labels to test dataset

In [3]:
edit_df = pd.read_pickle(r"C:\Users\Parv\Doc\HelixWorks\Basecalling\code\motifcaller\data\empirical\edit_distance_motif_search\edit_distance_motif_search.pkl")

In [4]:
edit_df

,read_id,orientation,motif_seq
0,7f177924-d279-4de6-bb86-01eaec9ee0e5,-,"[[3], [5], [2], [3], [], [], [], [], [], []]"
1,d47257cc-0209-450d-8b15-8c99a82dd1c4,-,"[[1], [8], [2], [5], [1], [5], [], [], [], []]"
2,6bf40594-e818-401a-a7f4-142b51615a14,-,"[[4], [2], [2], [1], [], [], [], [], [], []]"
3,07126fb4-14ef-4d7c-8be0-491c44e4ea8a,+,"[[1], [6], [6], [4], [], [], [], [], [], [8]]"
4,ccbd4335-1c81-4c06-a030-de9b231b0eed,-,"[[8], [2], [8], [2], [7], [8], [3], [2], [], []]"
...,...,...,...
590132,a3d4d1f1-5317-489a-b58e-548bf008b914,+,"[[], [], [4], [2], [5], [8], [7], [7], [6], [8]]"
590133,3c753ca5-9b01-4e70-9d67-527c53846aa0,-,"[[], [], [], [], [5], [], [], [], [], []]"
590134,7032acb2-5612-412e-8f2b-18d4be8eab13,-,"[[8], [5], [3], [5], [4], [8], [5], [5], [7], []]"
590135,84c36d62-3594-492e-9fae-b17a12944b54,+,"[[2], [5], [3], [3], [1], [7], [1], [5], [8], ..."
590136,56ba2729-433a-4e2c-9f24-29c6d03383bf,+,"[[3], [1], [4], [4], [4], [4], [8], [2], [2], ..."